const FOOD_DB = [
    // ─── PROTEINS ───────────────────────────────────────────────────────────────
    { name: 'Chicken Breast', serving: '4 oz (113g)', calories: 187, protein: 35, carbs: 0, fat: 4 },
    { name: 'Chicken Thigh', serving: '4 oz (113g)', calories: 229, protein: 28, carbs: 0, fat: 13 },
    { name: 'Ground Beef (93% Lean)', serving: '4 oz (113g)', calories: 200, protein: 28, carbs: 0, fat: 10 },
    { name: 'Ground Beef (80% Lean)', serving: '4 oz (113g)', calories: 287, protein: 23, carbs: 0, fat: 21 },
    { name: 'Ground Turkey', serving: '4 oz (113g)', calories: 170, protein: 22, carbs: 0, fat: 9 },
    { name: 'Sirloin Steak', serving: '4 oz (113g)', calories: 207, protein: 31, carbs: 0, fat: 9 },
    { name: 'Ribeye Steak', serving: '4 oz (113g)', calories: 310, protein: 26, carbs: 0, fat: 22 },
    { name: 'Salmon', serving: '4 oz (113g)', calories: 233, protein: 25, carbs: 0, fat: 14 },
    { name: 'Tuna (Canned in Water)', serving: '3 oz (85g)', calories: 100, protein: 22, carbs: 0, fat: 1 },
    { name: 'Tilapia', serving: '4 oz (113g)', calories: 145, protein: 30, carbs: 0, fat: 3 },
    { name: 'Shrimp', serving: '4 oz (113g)', calories: 112, protein: 24, carbs: 1, fat: 1 },
    { name: 'Pork Chop', serving: '4 oz (113g)', calories: 220, protein: 29, carbs: 0, fat: 11 },
    { name: 'Pork Tenderloin', serving: '4 oz (113g)', calories: 185, protein: 30, carbs: 0, fat: 6 },
    { name: 'Turkey Breast', serving: '4 oz (113g)', calories: 153, protein: 30, carbs: 0, fat: 3 },
    { name: 'Bacon', serving: '2 slices (28g)', calories: 87, protein: 6, carbs: 0, fat: 7 },
    { name: 'Breakfast Sausage', serving: '2 links (45g)', calories: 170, protein: 7, carbs: 1, fat: 15 },
    { name: 'Hot Dog', serving: '1 link (57g)', calories: 180, protein: 6, carbs: 2, fat: 16 },
    { name: 'Deli Turkey', serving: '2 oz (57g)', calories: 60, protein: 11, carbs: 1, fat: 1 },
    { name: 'Deli Ham', serving: '2 oz (57g)', calories: 70, protein: 10, carbs: 2, fat: 3 },
    { name: 'Beef Jerky', serving: '1 oz (28g)', calories: 116, protein: 9, carbs: 3, fat: 7 },
    { name: 'Bison (Ground)', serving: '4 oz (113g)', calories: 200, protein: 26, carbs: 0, fat: 10 },

    // ─── DAIRY / EGGS ────────────────────────────────────────────────────────────
    { name: 'Egg (Whole)', serving: '1 large', calories: 72, protein: 6, carbs: 0, fat: 5 },
    { name: 'Egg Whites', serving: '3 large whites', calories: 51, protein: 11, carbs: 1, fat: 0 },
    { name: 'Greek Yogurt (Plain)', serving: '6 oz (170g)', calories: 100, protein: 17, carbs: 6, fat: 0 },
    { name: 'Greek Yogurt (Flavored)', serving: '5.3 oz (150g)', calories: 140, protein: 12, carbs: 20, fat: 0 },
    { name: 'Regular Yogurt (Plain)', serving: '8 oz (227g)', calories: 149, protein: 9, carbs: 11, fat: 8 },
    { name: 'Cottage Cheese (Low Fat)', serving: '1/2 cup (113g)', calories: 90, protein: 13, carbs: 5, fat: 1 },
    { name: 'Whole Milk', serving: '1 cup (240ml)', calories: 149, protein: 8, carbs: 12, fat: 8 },
    { name: '2% Milk', serving: '1 cup (240ml)', calories: 122, protein: 8, carbs: 12, fat: 5 },
    { name: 'Skim Milk', serving: '1 cup (240ml)', calories: 83, protein: 8, carbs: 12, fat: 0 },
    { name: 'Cheddar Cheese', serving: '1 oz (28g)', calories: 114, protein: 7, carbs: 0, fat: 9 },
    { name: 'Mozzarella Cheese', serving: '1 oz (28g)', calories: 85, protein: 6, carbs: 1, fat: 6 },
    { name: 'Cream Cheese', serving: '2 tbsp (29g)', calories: 101, protein: 2, carbs: 2, fat: 10 },
    { name: 'Butter', serving: '1 tbsp (14g)', calories: 102, protein: 0, carbs: 0, fat: 12 },
    { name: 'Heavy Cream', serving: '2 tbsp (30ml)', calories: 101, protein: 1, carbs: 1, fat: 11 },
    { name: 'Whey Protein Powder', serving: '1 scoop (31g)', calories: 120, protein: 24, carbs: 3, fat: 2 },
    { name: 'Casein Protein Powder', serving: '1 scoop (33g)', calories: 120, protein: 24, carbs: 4, fat: 1 },

    // ─── GRAINS / CARBS ──────────────────────────────────────────────────────────
    { name: 'White Rice', serving: '1 cup cooked (186g)', calories: 242, protein: 4, carbs: 53, fat: 0 },
    { name: 'Brown Rice', serving: '1 cup cooked (195g)', calories: 216, protein: 5, carbs: 45, fat: 2 },
    { name: 'Oatmeal (Rolled Oats)', serving: '1 cup cooked (234g)', calories: 166, protein: 6, carbs: 28, fat: 4 },
    { name: 'Pasta (Cooked)', serving: '1 cup cooked (140g)', calories: 220, protein: 8, carbs: 43, fat: 1 },
    { name: 'White Bread', serving: '1 slice (25g)', calories: 67, protein: 2, carbs: 13, fat: 1 },
    { name: 'Whole Wheat Bread', serving: '1 slice (28g)', calories: 79, protein: 4, carbs: 14, fat: 1 },
    { name: 'Flour Tortilla', serving: '1 medium (45g)', calories: 146, protein: 4, carbs: 25, fat: 4 },
    { name: 'Corn Tortilla', serving: '1 medium (26g)', calories: 62, protein: 2, carbs: 13, fat: 1 },
    { name: 'Bagel (Plain)', serving: '1 medium (98g)', calories: 270, protein: 11, carbs: 53, fat: 1 },
    { name: 'English Muffin', serving: '1 whole (57g)', calories: 132, protein: 5, carbs: 26, fat: 1 },
    { name: 'Quinoa', serving: '1 cup cooked (185g)', calories: 222, protein: 8, carbs: 39, fat: 4 },
    { name: 'Couscous', serving: '1 cup cooked (157g)', calories: 176, protein: 6, carbs: 36, fat: 0 },
    { name: 'Sweet Potato', serving: '1 medium (130g)', calories: 112, protein: 2, carbs: 26, fat: 0 },
    { name: 'Potato (Russet)', serving: '1 medium (148g)', calories: 134, protein: 4, carbs: 30, fat: 0 },
    { name: 'Cream of Rice', serving: '1 cup cooked (244g)', calories: 127, protein: 2, carbs: 28, fat: 0 },
    { name: 'Rice Cakes (Plain)', serving: '2 cakes (18g)', calories: 70, protein: 1, carbs: 15, fat: 0 },
    { name: 'Granola', serving: '1/2 cup (59g)', calories: 298, protein: 6, carbs: 41, fat: 14 },
    { name: 'Cereal (Corn Flakes)', serving: '1 cup (28g)', calories: 101, protein: 2, carbs: 24, fat: 0 },

    // ─── FRUITS ──────────────────────────────────────────────────────────────────
    { name: 'Banana', serving: '1 medium (118g)', calories: 105, protein: 1, carbs: 27, fat: 0 },
    { name: 'Apple', serving: '1 medium (182g)', calories: 95, protein: 0, carbs: 25, fat: 0 },
    { name: 'Blueberries', serving: '1 cup (148g)', calories: 84, protein: 1, carbs: 21, fat: 0 },
    { name: 'Strawberries', serving: '1 cup (152g)', calories: 49, protein: 1, carbs: 12, fat: 0 },
    { name: 'Grapes', serving: '1 cup (92g)', calories: 62, protein: 1, carbs: 16, fat: 0 },
    { name: 'Orange', serving: '1 medium (131g)', calories: 62, protein: 1, carbs: 15, fat: 0 },
    { name: 'Mango', serving: '1 cup sliced (165g)', calories: 99, protein: 1, carbs: 25, fat: 1 },
    { name: 'Pineapple', serving: '1 cup chunks (165g)', calories: 82, protein: 1, carbs: 22, fat: 0 },
    { name: 'Avocado', serving: '1/2 medium (68g)', calories: 114, protein: 1, carbs: 6, fat: 10 },
    { name: 'Watermelon', serving: '1 cup (152g)', calories: 46, protein: 1, carbs: 11, fat: 0 },
    { name: 'Raspberries', serving: '1 cup (123g)', calories: 64, protein: 1, carbs: 15, fat: 1 },
    { name: 'Dried Cranberries', serving: '1/4 cup (40g)', calories: 123, protein: 0, carbs: 33, fat: 0 },
    { name: 'Raisins', serving: '1/4 cup (41g)', calories: 125, protein: 1, carbs: 33, fat: 0 },
    { name: 'Dates (Medjool)', serving: '2 dates (48g)', calories: 133, protein: 1, carbs: 36, fat: 0 },

    // ─── VEGETABLES ──────────────────────────────────────────────────────────────
    { name: 'Broccoli', serving: '1 cup chopped (91g)', calories: 31, protein: 3, carbs: 6, fat: 0 },
    { name: 'Spinach (Raw)', serving: '2 cups (60g)', calories: 14, protein: 2, carbs: 2, fat: 0 },
    { name: 'Kale (Raw)', serving: '1 cup (67g)', calories: 33, protein: 2, carbs: 6, fat: 0 },
    { name: 'Green Beans', serving: '1 cup (110g)', calories: 34, protein: 2, carbs: 8, fat: 0 },
    { name: 'Asparagus', serving: '6 spears (96g)', calories: 20, protein: 2, carbs: 4, fat: 0 },
    { name: 'Bell Pepper (Red)', serving: '1 medium (119g)', calories: 37, protein: 1, carbs: 7, fat: 0 },
    { name: 'Carrots', serving: '1 medium (61g)', calories: 25, protein: 1, carbs: 6, fat: 0 },
    { name: 'Tomato', serving: '1 medium (123g)', calories: 22, protein: 1, carbs: 5, fat: 0 },
    { name: 'Cucumber', serving: '1/2 medium (133g)', calories: 20, protein: 1, carbs: 5, fat: 0 },
    { name: 'Romaine Lettuce', serving: '2 cups (94g)', calories: 16, protein: 1, carbs: 3, fat: 0 },
    { name: 'Corn (Cooked)', serving: '1 ear (90g)', calories: 77, protein: 3, carbs: 17, fat: 1 },
    { name: 'Peas (Frozen/Cooked)', serving: '1/2 cup (80g)', calories: 62, protein: 4, carbs: 11, fat: 0 },
    { name: 'Onion', serving: '1/2 cup chopped (80g)', calories: 32, protein: 1, carbs: 7, fat: 0 },
    { name: 'Mushrooms', serving: '1 cup (70g)', calories: 15, protein: 2, carbs: 2, fat: 0 },
    { name: 'Cauliflower', serving: '1 cup chopped (107g)', calories: 27, protein: 2, carbs: 5, fat: 0 },
    { name: 'Zucchini', serving: '1 medium (196g)', calories: 33, protein: 2, carbs: 6, fat: 1 },
    { name: 'Brussels Sprouts', serving: '1 cup (88g)', calories: 38, protein: 3, carbs: 8, fat: 0 },
    { name: 'Sweet Corn (Canned)', serving: '1/2 cup (83g)', calories: 66, protein: 2, carbs: 15, fat: 1 },
    { name: 'Edamame (Shelled)', serving: '1/2 cup (78g)', calories: 94, protein: 9, carbs: 7, fat: 4 },

    // ─── NUTS / SEEDS / FATS ─────────────────────────────────────────────────────
    { name: 'Peanut Butter', serving: '2 tbsp (32g)', calories: 188, protein: 8, carbs: 7, fat: 16 },
    { name: 'Almond Butter', serving: '2 tbsp (32g)', calories: 196, protein: 7, carbs: 6, fat: 18 },
    { name: 'Almonds', serving: '1 oz (28g)', calories: 164, protein: 6, carbs: 6, fat: 14 },
    { name: 'Walnuts', serving: '1 oz (28g)', calories: 185, protein: 4, carbs: 4, fat: 18 },
    { name: 'Cashews', serving: '1 oz (28g)', calories: 157, protein: 5, carbs: 9, fat: 12 },
    { name: 'Peanuts', serving: '1 oz (28g)', calories: 161, protein: 7, carbs: 5, fat: 14 },
    { name: 'Chia Seeds', serving: '2 tbsp (20g)', calories: 97, protein: 3, carbs: 8, fat: 6 },
    { name: 'Flax Seeds (Ground)', serving: '2 tbsp (14g)', calories: 75, protein: 3, carbs: 4, fat: 6 },
    { name: 'Olive Oil', serving: '1 tbsp (14g)', calories: 119, protein: 0, carbs: 0, fat: 14 },
    { name: 'Coconut Oil', serving: '1 tbsp (14g)', calories: 121, protein: 0, carbs: 0, fat: 14 },
    { name: 'Mixed Nuts', serving: '1 oz (28g)', calories: 168, protein: 5, carbs: 7, fat: 15 },
    { name: 'Sunflower Seeds', serving: '1 oz (28g)', calories: 165, protein: 5, carbs: 7, fat: 14 },
    { name: 'Trail Mix', serving: '1/4 cup (40g)', calories: 173, protein: 4, carbs: 20, fat: 9 },

    // ─── LEGUMES ─────────────────────────────────────────────────────────────────
    { name: 'Black Beans (Cooked)', serving: '1/2 cup (86g)', calories: 114, protein: 8, carbs: 20, fat: 0 },
    { name: 'Kidney Beans (Cooked)', serving: '1/2 cup (89g)', calories: 112, protein: 8, carbs: 20, fat: 0 },
    { name: 'Chickpeas (Cooked)', serving: '1/2 cup (82g)', calories: 134, protein: 7, carbs: 22, fat: 2 },
    { name: 'Lentils (Cooked)', serving: '1/2 cup (99g)', calories: 115, protein: 9, carbs: 20, fat: 0 },
    { name: 'Hummus', serving: '2 tbsp (30g)', calories: 70, protein: 2, carbs: 4, fat: 6 },
    { name: 'Pinto Beans (Cooked)', serving: '1/2 cup (86g)', calories: 122, protein: 8, carbs: 22, fat: 1 },
    { name: 'Refried Beans', serving: '1/2 cup (126g)', calories: 120, protein: 7, carbs: 19, fat: 2 },

    // ─── SNACKS / BARS ───────────────────────────────────────────────────────────
    { name: 'Protein Bar (Quest Style)', serving: '1 bar (60g)', calories: 200, protein: 21, carbs: 21, fat: 7 },
    { name: 'Granola Bar', serving: '1 bar (47g)', calories: 193, protein: 4, carbs: 29, fat: 8 },
    { name: 'Rice Krispie Treat', serving: '1 bar (43g)', calories: 174, protein: 1, carbs: 36, fat: 4 },
    { name: 'Dark Chocolate (70%)', serving: '1 oz (28g)', calories: 170, protein: 2, carbs: 13, fat: 12 },
    { name: 'Popcorn (Air Popped)', serving: '3 cups (24g)', calories: 93, protein: 3, carbs: 19, fat: 1 },
    { name: 'Pretzels', serving: '1 oz (28g)', calories: 108, protein: 3, carbs: 23, fat: 1 },
    { name: 'Potato Chips', serving: '1 oz (28g)', calories: 152, protein: 2, carbs: 15, fat: 10 },
    { name: 'Crackers (Wheat Thins)', serving: '16 crackers (31g)', calories: 140, protein: 2, carbs: 22, fat: 5 },

    // ─── DRINKS ──────────────────────────────────────────────────────────────────
    { name: 'Protein Shake (Premade)', serving: '1 bottle (325ml)', calories: 160, protein: 30, carbs: 6, fat: 3 },
    { name: 'Orange Juice', serving: '8 oz (240ml)', calories: 112, protein: 2, carbs: 26, fat: 0 },
    { name: 'Apple Juice', serving: '8 oz (240ml)', calories: 114, protein: 0, carbs: 28, fat: 0 },
    { name: 'Chocolate Milk (2%)', serving: '1 cup (240ml)', calories: 190, protein: 8, carbs: 30, fat: 5 },
    { name: 'Almond Milk (Unsweetened)', serving: '1 cup (240ml)', calories: 37, protein: 1, carbs: 2, fat: 3 },
    { name: 'Oat Milk', serving: '1 cup (240ml)', calories: 120, protein: 3, carbs: 16, fat: 5 },
    { name: 'Soda (Cola)', serving: '12 oz (355ml)', calories: 140, protein: 0, carbs: 39, fat: 0 },
    { name: 'Beer (Regular)', serving: '12 oz (355ml)', calories: 153, protein: 1, carbs: 13, fat: 0 },
    { name: 'Wine (Red)', serving: '5 oz (148ml)', calories: 125, protein: 0, carbs: 4, fat: 0 },
    { name: 'Sports Drink (Gatorade)', serving: '12 oz (355ml)', calories: 80, protein: 0, carbs: 22, fat: 0 },
    { name: 'Coconut Water', serving: '8 oz (240ml)', calories: 46, protein: 2, carbs: 9, fat: 0 },
    { name: 'Coffee (Black)', serving: '8 oz (240ml)', calories: 2, protein: 0, carbs: 0, fat: 0 },
    { name: 'Latte (Whole Milk)', serving: '12 oz (355ml)', calories: 204, protein: 10, carbs: 16, fat: 10 },

    // ─── COMMON MEALS ────────────────────────────────────────────────────────────
    { name: 'Pizza Slice (Cheese)', serving: '1 slice (107g)', calories: 285, protein: 12, carbs: 36, fat: 10 },
    { name: 'Hamburger', serving: '1 burger (215g)', calories: 540, protein: 27, carbs: 40, fat: 28 },
    { name: 'Cheeseburger', serving: '1 burger (228g)', calories: 590, protein: 30, carbs: 40, fat: 32 },
    { name: 'Grilled Cheese Sandwich', serving: '1 sandwich (120g)', calories: 378, protein: 14, carbs: 32, fat: 22 },
    { name: 'PB&J Sandwich', serving: '1 sandwich (100g)', calories: 390, protein: 13, carbs: 52, fat: 17 },
    { name: 'Chicken Wrap', serving: '1 wrap (250g)', calories: 430, protein: 35, carbs: 40, fat: 12 },
    { name: 'Burrito (Chicken)', serving: '1 burrito (300g)', calories: 480, protein: 32, carbs: 54, fat: 14 },
    { name: 'Taco (Chicken)', serving: '1 taco (120g)', calories: 210, protein: 14, carbs: 18, fat: 8 },
    { name: 'Sushi Roll (California)', serving: '8 pieces (220g)', calories: 255, protein: 9, carbs: 38, fat: 7 },
    { name: 'Mac and Cheese', serving: '1 cup (252g)', calories: 350, protein: 14, carbs: 50, fat: 10 },
    { name: 'Ramen (Instant)', serving: '1 package (85g dry)', calories: 380, protein: 9, carbs: 54, fat: 14 },
    { name: 'Fried Rice', serving: '1 cup (198g)', calories: 338, protein: 10, carbs: 50, fat: 12 },
    { name: 'Stir Fry Chicken', serving: '1 cup (240g)', calories: 280, protein: 30, carbs: 15, fat: 10 },
    { name: 'Chicken Nuggets (Fast Food)', serving: '6 pieces (99g)', calories: 280, protein: 16, carbs: 17, fat: 17 },
    { name: 'French Fries (Fast Food)', serving: 'Medium (117g)', calories: 365, protein: 4, carbs: 48, fat: 17 },
    { name: 'Mashed Potatoes', serving: '1 cup (210g)', calories: 210, protein: 4, carbs: 35, fat: 7 },
    { name: 'Pancakes (Plain)', serving: '2 medium (130g)', calories: 268, protein: 8, carbs: 40, fat: 9 },
    { name: 'Waffles (Plain)', serving: '2 waffles (130g)', calories: 296, protein: 8, carbs: 41, fat: 11 },
    { name: 'Omelette (3 Egg)', serving: '1 omelette (195g)', calories: 307, protein: 22, carbs: 3, fat: 23 },
    { name: 'Scrambled Eggs (2)', serving: '2 eggs cooked (88g)', calories: 169, protein: 12, carbs: 2, fat: 12 },

    // ─── ADDITIONAL PROTEINS ─────────────────────────────────────────────────────
    { name: 'Cod Fillet', serving: '4 oz (113g)', calories: 93, protein: 20, carbs: 0, fat: 1 },
    { name: 'Canned Salmon', serving: '3 oz (85g)', calories: 130, protein: 17, carbs: 0, fat: 6 },
    { name: 'Turkey Sausage', serving: '2 links (56g)', calories: 130, protein: 13, carbs: 1, fat: 8 },
    { name: 'Rotisserie Chicken', serving: '3 oz (85g)', calories: 148, protein: 22, carbs: 0, fat: 6 },
    { name: 'Ham Steak', serving: '4 oz (113g)', calories: 163, protein: 26, carbs: 0, fat: 6 },
    { name: 'Lamb Chop', serving: '4 oz (113g)', calories: 240, protein: 29, carbs: 0, fat: 13 },
    { name: 'Scallops', serving: '4 oz (113g)', calories: 100, protein: 19, carbs: 5, fat: 1 },
    { name: 'Crab Meat', serving: '3 oz (85g)', calories: 87, protein: 17, carbs: 0, fat: 2 },

    // ─── ADDITIONAL DAIRY / EGGS ──────────────────────────────────────────────────
    { name: 'String Cheese', serving: '1 stick (28g)', calories: 80, protein: 7, carbs: 0, fat: 5 },
    { name: 'Ricotta Cheese (Part Skim)', serving: '1/4 cup (62g)', calories: 86, protein: 7, carbs: 3, fat: 5 },
    { name: 'Parmesan Cheese', serving: '2 tbsp (10g)', calories: 43, protein: 4, carbs: 0, fat: 3 },
    { name: 'Half and Half', serving: '2 tbsp (30ml)', calories: 39, protein: 1, carbs: 1, fat: 3 },

    // ─── ADDITIONAL GRAINS / CARBS ────────────────────────────────────────────────
    { name: 'Sourdough Bread', serving: '1 slice (47g)', calories: 120, protein: 5, carbs: 23, fat: 1 },
    { name: 'Pita Bread', serving: '1 medium (57g)', calories: 165, protein: 5, carbs: 33, fat: 1 },
    { name: 'Cornbread', serving: '1 piece (65g)', calories: 198, protein: 4, carbs: 29, fat: 8 },
    { name: 'Breadstick (Plain)', serving: '1 breadstick (20g)', calories: 77, protein: 2, carbs: 14, fat: 2 },
    { name: 'Jasmine Rice', serving: '1 cup cooked (186g)', calories: 238, protein: 4, carbs: 52, fat: 0 },
    { name: 'Farro (Cooked)', serving: '1 cup cooked (200g)', calories: 250, protein: 10, carbs: 46, fat: 2 },

    // ─── ADDITIONAL FRUITS ────────────────────────────────────────────────────────
    { name: 'Peach', serving: '1 medium (150g)', calories: 59, protein: 1, carbs: 14, fat: 0 },
    { name: 'Pear', serving: '1 medium (178g)', calories: 101, protein: 1, carbs: 27, fat: 0 },
    { name: 'Cherries', serving: '1 cup (138g)', calories: 87, protein: 1, carbs: 22, fat: 0 },
    { name: 'Kiwi', serving: '1 medium (76g)', calories: 46, protein: 1, carbs: 11, fat: 0 },
    { name: 'Cantaloupe', serving: '1 cup cubed (160g)', calories: 54, protein: 1, carbs: 13, fat: 0 },

    // ─── ADDITIONAL VEGETABLES ───────────────────────────────────────────────────
    { name: 'Celery', serving: '2 stalks (80g)', calories: 12, protein: 1, carbs: 3, fat: 0 },
    { name: 'Beets', serving: '1/2 cup cooked (85g)', calories: 37, protein: 1, carbs: 8, fat: 0 },
    { name: 'Artichoke Hearts', serving: '1/2 cup (84g)', calories: 45, protein: 2, carbs: 10, fat: 0 },
    { name: 'Eggplant', serving: '1 cup cooked (99g)', calories: 35, protein: 1, carbs: 9, fat: 0 },

    // ─── ADDITIONAL NUTS / FATS ───────────────────────────────────────────────────
    { name: 'Macadamia Nuts', serving: '1 oz (28g)', calories: 204, protein: 2, carbs: 4, fat: 21 },
    { name: 'Pistachios', serving: '1 oz (28g)', calories: 159, protein: 6, carbs: 8, fat: 13 },
    { name: 'Hemp Seeds', serving: '3 tbsp (30g)', calories: 166, protein: 10, carbs: 3, fat: 15 },
    { name: 'Pumpkin Seeds', serving: '1 oz (28g)', calories: 151, protein: 7, carbs: 5, fat: 13 },
    { name: 'Tahini', serving: '1 tbsp (15g)', calories: 89, protein: 3, carbs: 3, fat: 8 },
    { name: 'Coconut (Shredded)', serving: '2 tbsp (11g)', calories: 71, protein: 1, carbs: 3, fat: 7 },

    // ─── ADDITIONAL SNACKS ────────────────────────────────────────────────────────
    { name: 'Protein Bar (Clif Bar)', serving: '1 bar (68g)', calories: 250, protein: 10, carbs: 44, fat: 6 },
    { name: 'Fruit Snacks', serving: '1 pouch (23g)', calories: 80, protein: 0, carbs: 19, fat: 0 },
    { name: 'Graham Crackers', serving: '2 sheets (28g)', calories: 118, protein: 2, carbs: 22, fat: 3 },
    { name: 'Oreo Cookies', serving: '3 cookies (34g)', calories: 160, protein: 1, carbs: 25, fat: 7 },

    // ─── ADDITIONAL DRINKS ────────────────────────────────────────────────────────
    { name: 'Green Tea (Unsweetened)', serving: '8 oz (240ml)', calories: 2, protein: 0, carbs: 0, fat: 0 },
    { name: 'Energy Drink (Monster)', serving: '8 oz (240ml)', calories: 100, protein: 1, carbs: 27, fat: 0 },
    { name: 'Kombucha', serving: '8 oz (240ml)', calories: 30, protein: 0, carbs: 7, fat: 0 },
    { name: 'Smoothie (Green)', serving: '12 oz (355ml)', calories: 180, protein: 4, carbs: 38, fat: 3 },
    { name: 'Protein Coffee (RTD)', serving: '11 oz (325ml)', calories: 130, protein: 20, carbs: 10, fat: 2 },

    // ─── ADDITIONAL MEALS ─────────────────────────────────────────────────────────
    { name: 'Egg Sandwich (Fast Food)', serving: '1 sandwich (138g)', calories: 300, protein: 13, carbs: 30, fat: 14 },
    { name: 'Burrito Bowl (Chicken)', serving: '1 bowl (400g)', calories: 570, protein: 40, carbs: 58, fat: 17 },
    { name: 'Gyro', serving: '1 sandwich (250g)', calories: 500, protein: 28, carbs: 44, fat: 22 },
    { name: 'Pad Thai', serving: '1 cup (200g)', calories: 330, protein: 16, carbs: 44, fat: 10 },
    { name: 'Chicken Quesadilla', serving: '1 quesadilla (220g)', calories: 480, protein: 33, carbs: 38, fat: 22 },
    { name: 'Greek Salad', serving: '1 large (350g)', calories: 320, protein: 8, carbs: 18, fat: 24 },
    { name: 'Chicken Caesar Salad', serving: '1 large (350g)', calories: 480, protein: 36, carbs: 20, fat: 28 },
    { name: 'Turkey Club Sandwich', serving: '1 sandwich (280g)', calories: 540, protein: 38, carbs: 42, fat: 22 },

    // ─── CONDIMENTS / EXTRAS ─────────────────────────────────────────────────────
    { name: 'Honey', serving: '1 tbsp (21g)', calories: 64, protein: 0, carbs: 17, fat: 0 },
    { name: 'Maple Syrup', serving: '1 tbsp (20g)', calories: 52, protein: 0, carbs: 13, fat: 0 },
    { name: 'Ketchup', serving: '1 tbsp (17g)', calories: 17, protein: 0, carbs: 5, fat: 0 },
    { name: 'Mustard (Yellow)', serving: '1 tbsp (15g)', calories: 9, protein: 1, carbs: 1, fat: 0 },
    { name: 'Mayonnaise', serving: '1 tbsp (14g)', calories: 94, protein: 0, carbs: 0, fat: 10 },
    { name: 'Ranch Dressing', serving: '2 tbsp (30g)', calories: 143, protein: 0, carbs: 2, fat: 15 },
    { name: 'Soy Sauce', serving: '1 tbsp (16g)', calories: 9, protein: 1, carbs: 1, fat: 0 },
    { name: 'BBQ Sauce', serving: '2 tbsp (36g)', calories: 54, protein: 0, carbs: 13, fat: 0 },
    { name: 'Hot Sauce (Tabasco)', serving: '1 tsp (5g)', calories: 1, protein: 0, carbs: 0, fat: 0 },
    { name: 'Salsa', serving: '2 tbsp (30g)', calories: 10, protein: 0, carbs: 2, fat: 0 },
    { name: 'Guacamole', serving: '2 tbsp (30g)', calories: 45, protein: 1, carbs: 2, fat: 4 },
    { name: 'Sour Cream', serving: '2 tbsp (29g)', calories: 60, protein: 1, carbs: 1, fat: 6 },
    { name: 'Jam / Jelly', serving: '1 tbsp (20g)', calories: 56, protein: 0, carbs: 14, fat: 0 },
];
